#!/bin/sh

mkdir INV-ver-htc01
cd INV-ver-htc01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-sub01
cd INV-ver-sub01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-cer01
cd INV-ver-cer01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-des01
cd INV-ver-des01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-agw01
cd INV-ver-agw01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-vdm01
cd INV-ver-vdm01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-wfi01
cd INV-ver-wfi01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-esp01
cd INV-ver-esp01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-rmt01
cd INV-ver-rmt01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-esw01
cd INV-ver-esw01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-tcu01
cd INV-ver-tcu01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-vky01
cd INV-ver-vky01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
mkdir INV-ver-htc01
cd INV-ver-htc01
mkdir src
cd src
mkdir handlers
cd handlers
mkdir my_lambda_function
cd ~/cicd_cn
